### ISSUE TITLE
thumbnails, tags

### ISSUE THREAD

**Issue by mmega** [whyboris/Video-Hub-App#355] opened 2020-02-09 09:22 UTC
thumbnails view - compact view
Sometimes can't see all thumbnails
Scroll down all see
![20200209_173024](https://user-images.githubusercontent.com/57275671/74099219-906b8600-4b64-11ea-962c-bacc20d3f917.jpg)

details view - show manual tags 
Times played 0 all visible, Times played 1 not all visible
![20200209_173929](https://user-images.githubusercontent.com/57275671/74099221-906b8600-4b64-11ea-8c21-9cf8628e4fdb.jpg)

Thanks

**Comment by whyboris** [comment] 2020-02-10 01:15
Thank you for opening this issue. I hope I can understand what the issue is; it seems like you're reporting 2 bugs?

1) In the first screenshot you do not see all thumbnails showing
    - (even though the view has more of them -- I can see the scrollbar size indicates there are more) 
    - I suspect once you start scrolling they all show up, is that correct?
    - The issue is _not_ about the screenshots all being black (as if no thumbnails were extracted), right?

This is a known (to me) issue (and it's very minor, I think)
    - It's only a bit annoying (since on-scroll everything appears) but is also probably easy to fix; 
    - would be great if someone could track down where in the code we need to fix it 
    - (I suspect it's a matter of forcing the virtual-scroller to update its view 🤷‍♂ )

2) In _details_ view, the app indicates that you have watched a video more than 1 time, but does _not_ indicate when you've never opened a video (through the app).
    - **This is intended behavior** (I programmed it this way on purpose)
    - Do you think it would be better if it always showed "_Played 0 times_" when the video hasn't been opened through the app yet?

Please let me know if I've misunderstood the issues.

**Comment by mmega** [comment] 2020-02-10 05:25
First of all, I'm using this software very well. 
I'm sorry i didn't have enough explanation. All thumbnails are normal. I covered it with a black box. 
I couldn't show all the thumbnails and letters.
I'll reattach it and explain it. 

1. Sometimes [thumbnails view-compact view] doesn't see all the thumbnails, so I wanted to let you know.
Attached a gif. 4.51mb
![20200210_133415](https://user-images.githubusercontent.com/57275671/74123004-8606c600-4c10-11ea-94d8-94038296ac84.gif)



2. I use auto-generated tags and manual tags. view it using manual tags.
see the video more than once, the tagbox, letters will be pushed down and truncated?cut off?
I just hope to see all the tags and letters.
![20200210_143611](https://user-images.githubusercontent.com/57275671/74122613-34aa0700-4c0f-11ea-89c3-c20953c3053e.JPG)

**Comment by whyboris** [comment] 2020-02-13 20:14
Thank you very much for the images!

I think I understand both issues correctly now. I'll see if I can fix them by the next release 🙂

**Comment by whyboris** [comment] 2020-02-13 23:20
I fixed issue (2) with #362 I think -- will be released along in the next release 👍 
I'll see about (1) too sometime 🤝

**Comment by jamesd35** [comment] 2020-06-28 21:07
What exactly is the issue in the first case? Not sure I'm understanding correctly. Sometimes not all of the thumbnails display?

**Comment by whyboris** [comment] 2020-06-28 21:53
🤷  I'm unsure how important it is to fix this problem -- as far as I understand there are times when you switch to the gallery view and there are empty spots, as if you're seeing the end of the gallery (when in fact there are many more videos). They appear as soon as you start scrolling. 🤔 

**It's very low priority** -- and I guess I kept it open in case someone stumbles across what they think could be a fix.

I imagine one way to fix is to simply call "recalculate" (or whatever method it is) on _virtual-scroller_ 

It looks like it can be replicated when you click on "compact view" ... though in the past I've seen it happen when just opening the thumbnail gallery 🤔

**Comment by orkomlosh** [comment] 2020-08-10 15:33
Is it still happenning?
I can take a look.

Btw @whyboris i want to help with new features. Or more complicated issues.
Let me know if you want, and how we can collaborate on that.

**Comment by whyboris** [comment] 2020-08-10 16:10
Hey @orkomlosh -- thank you again for your previous contributions 😁 

Feel free to take anything that you find interesting! The other issues you commented on where others have called dibs but haven't done anything in over 2 weeks I think are free for the taking too 🤔 

Last week I took a work vacation (staycation) was hoping to do some work on VHA but had a 4-day power outage due to a storm 😅 read some books instead 👌 This week I'll try to clean up the `main` branch some more - focusing on all the possible bugs that could happen with multi-folder extraction and switching between hubs while extraction happens 😓 

I love you enthusiasm -- I think it's best to work on whatever is most interesting to you 👍 Please feel free to reach out with any questions 🤝 and feel free to create new issues to discuss any features you'd want to add too 🙌

**Comment by orkomlosh** [comment] 2020-08-10 16:40
Thanks, 
It's a great product with very interesting architecture and tech.
Very happy to get across it, and that you are welcoming new contributors with such nice vibe.

I will need to dive deep in to it, in order to understand it better.
Angular is something i'm partly doing on my day job. And node i knew from automation dev so it's a little bit different.
I'll try to take some more of the opened bugs to learn the system flow better.

**Comment by whyboris** [comment] 2020-08-10 17:24
I'm happy to answer questions. As you look through code, keep in mind my implementation can be improved in many places (I'm sure) -- I started the app just months after I started learning Angular and I haven't had much node experience (other than some server work at my job - which had no file system interaction). 

If you see something that you think can be better -- feel free to add a fix, or start a discussion if it's a larger task and you suspect I might have reasons behind my sub-optimal decisions.

One thing I've been considering doing is to move the `ImageElement[]` (array of all the videos) to a dedicated _service_ rather than keep it around in the `home.component`. Feels like it would make interactions from other components easier.

In the past I had (children) components emit updates to update a video -- not realizing that since they receive the data by reference, I could update the properties within the child component directly 🤔 

I'm particularly happy about how the search/filter works -- just passing data through many pipes before it gets rendered 😁 -- I was surprised at how quickly the whole funnel works even with thousands of videos 🤷 

The heart of the app is the [ngx-virtual-scroller](https://github.com/rintoj/ngx-virtual-scroller) which lets us display thousands of videos without overloading the DOM.

The HTML & CSS for the layout is rather hack-y, but it works well enough for now. One UI (user interface) problem I'm facing is the import indicator (donut progress bar on top-right). It stays even when the top ribbon (with folder & file name) gets collapsed, thus overlapping with the settings button (the gear). I'm unsure how to handle this with the UI 🤔 

Another bit of cleanup I've been meaning to do is #420 cleaning up the click-emissions (the interface is really convoluted at the moment). The code works as desired, but it's not elegant at all.

**Comment by whyboris** [comment] 2020-08-10 17:35
I'm happy to answer questions. As you look through code, keep in mind my implementation can be improved in many places (I'm sure) -- I started the app just months after I started learning Angular and I haven't had much node experience (other than some server work at my job - which had no file system interaction). 

If you see something that you think can be better -- feel free to add a fix, or start a discussion if it's a larger task and you suspect I might have reasons behind my sub-optimal decisions.

### Some random thoughts:
- One thing I've been considering doing is to move the `ImageElement[]` (array of all the videos) to a dedicated _service_ rather than keep it around in the `home.component`. Feels like it would make interactions from other components easier.

- In the past I had (children) components emit updates to update a video -- not realizing that since they receive the data by reference, I could update the properties within the child component directly 🤔 

- I'm particularly happy about how the search/filter works -- just passing data through many pipes before it gets rendered 😁 -- I was surprised at how quickly the whole funnel works even with thousands of videos 🤷 

- The heart of the app is the [ngx-virtual-scroller](https://github.com/rintoj/ngx-virtual-scroller) which lets us display thousands of videos without overloading the DOM.

- The HTML & CSS for the layout is rather hack-y, but it works well enough for now. One UI (user interface) problem I'm facing is the import indicator (donut progress bar on top-right). It stays even when the top ribbon (with folder & file name) gets collapsed, thus overlapping with the settings button (the gear). I'm unsure how to handle this with the UI 🤔 

- Another bit of cleanup I've been meaning to do is #420 cleaning up the click-emissions (the interface is really convoluted at the moment). The code works as desired, but it's not elegant at all.

**Comment by orkomlosh** [comment] 2020-08-10 18:16
thanks for the short overview it's very helpful.
i'll try to continue with the small bugs and issues for now.
and will continue to learn as I go
BTW pretty impressive road you got there!

Good luck!

**Closed** 2020-08-10 22:07 UTC
Labels: good first issue, help wanted
