### ISSUE TITLE
could not buy from the web

### ISSUE THREAD

**Issue by msongz** [whyboris/Video-Hub-App#188] opened 2019-06-06 03:50 UTC
always circle after click "buy"
chrome 75
macos 10.13.6

and success on safari

**Comment by whyboris** [comment] 2019-06-09 14:45
Thank you for the bug report! 

I just tried it out and though it took an unexpectedly long time (30 seconds?) the _buy_ modal showed up on all three: _Chrome_, _Firefox_, and _Safari_ (testing on a Mac).
Logging in to the _Chec_ dashboard, it takes a long-ish time to load -- so I suspect _Chec_ is having some server issues 😅 
Hope it returns to working as quickly as before. Though I am testing from Tokyo right now, so maybe it's the trans-Atlantic cable or some similar network issues 🤔 

Thank you for the purchase songZ 🙇 
Continued support like yours is what inspires me to continue working on the app 🙌

**Comment by whyboris** [comment] 2019-07-14 16:22
Thank you again _msongz_ for documenting the bug and for the subsequent purchase 🙇 

I'm closing this issue as it is likely a sporadic problem - I've not been able to reproduce, and I'm seeing about 2 purchases per day over the past many months. 

If anyone runs into trouble, please contact me or open a new issue 🙇

**Closed by whyboris** 2019-07-14 16:22 UTC

**Comment by whangwang** [comment] 2019-07-17 10:18
same issue happened on me.
try using chrome, safari, firefox but get same result.
mac 10.14.5

**Comment by whyboris** [comment] 2019-07-17 13:30
@whangwang -- sounds like you were not able to purchase the app from any of the three browsers 😱 ?

When you visit https://videohubapp.com/download.html and click `Buy Now` do you see this?

![image](https://user-images.githubusercontent.com/17264277/61379349-5ad41800-a875-11e9-9668-7f35f00ac8d6.png)

I have had one person email me having trouble purchasing - it turns out that they hadn't entered the purchase amount (it's a minimum $3.50, but the value needs to be entered manually). 

Could this be the problem you're facing?

**Comment by whangwang** [comment] 2019-07-17 15:54
hi, thanks for your reply! (sorry for my poor english)

no this modal didn't pop up, it just keep showing loading animation, and i tried to lookup at dev tool's network tab, seems like chec.io return "Access Blocked" on purchase request. (see screenshot below)

![image](https://user-images.githubusercontent.com/16395064/61390747-eee1c600-a8ed-11e9-9d36-37ef221ba583.png)

Again, thanks for your reply!

**Comment by whyboris** [comment] 2019-07-17 17:33
This is really unfortunate -- could it be related to a firewall in China? 
(I know very little about it -- I just have heard that some websites are blocked) 
The modal comes up for me instantly 😕 

What about this direct website?
https://spaces.chec.io/13932

**Comment by whyboris** [comment] 2019-07-17 17:35
ps -- I'm loving the navigation on your website: whangwang.github.io
I'll be using it for the upcoming VHA website redesign 🙇 
Thank you for sharing the code and the source where it came from: https://github.com/whangwang/whangwang.github.io 🙌

**Comment by whyboris** [comment] 2019-07-17 18:03
pps - I also created a pull request to remove some unneeded stuff from your website 😉 
https://github.com/whangwang/whangwang.github.io/pull/1

**Comment by whyboris** [comment] 2019-07-18 00:48
ppps - works great, but need to get it to work on mobile too 😅 
https://videohubapp.com/about.html

**Comment by whangwang** [comment] 2019-07-18 02:32
hi, actually i come from Taiwan, and I also tried using VPN but still can't work 
i still get "Access Blocked" from the direct url link

and thanks for your love about my website,
but this effect is actually reference by 
[https://tympanus.net/Development/PerspectivePageViewNavigation/](https://tympanus.net/Development/PerspectivePageViewNavigation/)
so visit that site may help you get more information about this!

and yes, this is my website about two yeas ago, so there will be a lot of stupid stuff in code 😂😂
anyway, thanks for your pull request.

ps. my new website is [https://han.gallery](https://han.gallery) , so if you feel interested about it, please visit and give me some advice! (also it's full of Chineses, so I don't think you can understand it very clearly😂, I'll tried to translate it to English in future!)

**Comment by whyboris** [comment] 2019-07-18 02:57
Sorry to hear you're having so much trouble with the payment.
I certainly want to fix this so _everyone_ is able to buy if they are interested.
Meanwhile -- please message me your email through the website contact form:
https://videohubapp.com/contact.html
Cheers! 😄
