### ISSUE TITLE
Drag videos outside of app throws error

### ISSUE THREAD

**Issue by Manusan42** [whyboris/Video-Hub-App#632] opened 2021-01-23 10:01 UTC
As soon I activate this function and drag a video, I get this error:
![drag error](https://user-images.githubusercontent.com/12750571/105575181-0c58e100-5d6a-11eb-8a45-6cbf7b7430a7.png)

My OS:
Edition	Windows 10 Pro
Version	20H2
OS build	19042.746

**Comment by whyboris** [comment] 2021-01-26 01:29
Thank you for sharing the bug (duplicate of #607). 

It has been fixed (#608) and will be released in the next public release `3.1.0`

The code is already in `main` ✅

**Closed by whyboris** 2021-01-26 01:29 UTC
